version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    assignees:
      - egorovli

  - package-ecosystem: npm
    directory: /packages/api
    schedule:
      interval: weekly
      day: monday
    assignees:
      - egorovli

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    assignees:
      - egorovli